name: Triggered by Version Bump Release PR

on:
  pull_request:
    paths:
      - '!**'
      - "sovtoken/sovtoken/metadata.json"
      - "sovtokenfees/sovtokenfees/metadata.json"

jobs:
  release-infos:
    name: infos
    runs-on: ubuntu-latest
    outputs:
      isVersionBump: ${{ steps.get-release-info.outputs.isVersionBump }}
      isPreRelease: ${{ steps.get-release-info.outputs.isRC }}
      CACHE_KEY_BUILD: ${{ steps.workflow-setup.outputs.CACHE_KEY_BUILD }}
      UBUNTU_VERSION: ${{ steps.workflow-setup.outputs.UBUNTU_VERSION }}
      # Expose the lowercase version of the GitHub repository name
      # to all subsequent jobs that reference image repositories
      # as the push and pull operations require the URL of the repository
      # to be in lowercase.
      GITHUB_REPOSITORY_NAME: ${{ steps.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
      distribution: ${{ steps.workflow-setup.outputs.distribution }}
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
      - name: get-release-info
        id: get-release-info
        uses: hyperledger/indy-shared-gha/.github/actions/get-release-info@v1
        with:
          versionString: "${{ github.event.pull_request.body }}"
      - name: workflow-setup
        id: workflow-setup
        uses: hyperledger/indy-shared-gha/.github/actions/workflow-setup@v1

  lint:
    name: Lint
    needs: [release-infos]
#     if: ${{ needs.release-infos.outputs.testsNeeded == 'true' }}
    uses: hyperledger/indy-shared-gha/.github/workflows/lint.yaml@v1

  build-image:
    name: Create Builder Image
    needs: [release-infos]
    if: ${{ always() }}
    uses: hyperledger/indy-shared-gha/.github/workflows/buildimage.yaml@v1
    with:
      CACHE_KEY_BUILD: ${{ needs.release-infos.outputs.CACHE_KEY_BUILD }}
      DOCKER_IMAGE: ghcr.io/${{ needs.release-infos.outputs.GITHUB_REPOSITORY_NAME }}/token-plugin-build
      UBUNTU_VERSION: ${{ needs.release-infos.outputs.UBUNTU_VERSION }}

  token-plugin-tests:
    name: Token Plugin Tests
    needs: [workflow-setup, build-image]
    uses: ./.github/workflows/reuseable_test.yaml
    with:
      GITHUB_REPOSITORY_NAME: ${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
      UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}    

  build-package:
    name: Token Plugin Build package
    needs: [release-infos, build-image]
    uses: ./.github/workflows/reuseable_build_package.yaml
    with:
      GITHUB_REPOSITORY_NAME: ${{ needs.release-infos.outputs.GITHUB_REPOSITORY_NAME }}
      UBUNTU_VERSION: ${{ needs.release-infos.outputs.UBUNTU_VERSION }}    
