name: "Build Token Plugin Package"

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        required: true
        type: string
      UBUNTU_VERSION:
        required: true
        type: string
      isDev:
        required: false
        default: true
        type: boolean

jobs:
  timestamp:
    name: Get timestamp
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"

  build_token_plugin_release:
    name: Token Plugin Build Packages
    needs: timestamp
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/${{ inputs.GITHUB_REPOSITORY_NAME }}/token-plugin-build:${{ inputs.UBUNTU_VERSION }}
    steps:
      - name: adding github workspace as safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set Version with UX-timestamp
        if: ${{ inputs.isDev }}
        run: python3 updateVersion.py --timestamp ${{ needs.timestamp.outputs.timestamp }}
      - name: Build Token Plugin deployment package
        run: |
          mkdir -p /tmp/build-output
          fpm  --input-type dir --output-type deb --name sovtoken  --version latest --depends "indy-node(=1.13.0~dev1225)" --verbose --no-python-dependencies --force  sovtoken/
          fpm  --input-type dir --output-type deb --name sovtokenfees  --version latest --depends "indy-node(=1.13.0~dev1225)" --verbose --no-python-dependencies --force  sovtokenfees/
          mv ./*.deb /tmp/build-output
      - name: Upload sovtoken-deb
        uses: actions/upload-artifact@v2
        with:
          name: sovtoken-deb
          path: /tmp/build-output/sovtoken_*.deb
      - name: Upload sovtokenfees-deb
        uses: actions/upload-artifact@v2
        with:
          name: sovtokenfees-deb
          path: /tmp/build-output/sovtokenfees_*.deb

  build_sovtoken_pypi:
    name: sovtoken Build Package
    runs-on: ubuntu-20.04
    needs: timestamp
    container:
      image: ghcr.io/${{ inputs.GITHUB_REPOSITORY_NAME }}/token-plugin-build:${{ inputs.UBUNTU_VERSION }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set Version with UX-timestamp
        if: ${{ inputs.isDev }}
        run: python3 updateVersion.py --timestamp ${{ needs.timestamp.outputs.timestamp }}
      - name: Build python sovtoken package
        run: python3 sovtoken/setup.py sdist --dist-dir /tmp/dist bdist_wheel --dist-dir /tmp/dist
      - uses: actions/upload-artifact@v2
        with:
          name: sovtoken-python
          path: /tmp/dist
          retention-days: 5

  build_sovtokenfees_pypi:
    name: sovtokenfees Build Packages
    runs-on: ubuntu-20.04
    needs: timestamp
    container:
      image: ghcr.io/${{ inputs.GITHUB_REPOSITORY_NAME }}/token-plugin-build:${{ inputs.UBUNTU_VERSION }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set Version with UX-timestamp
        if: ${{ inputs.isDev }}
        run: python3 updateVersion.py --timestamp ${{ needs.timestamp.outputs.timestamp }}
      - name: Build python sovtokenfees package
        run: python3 sovtokenfees/setup.py sdist --dist-dir /tmp/dist bdist_wheel --dist-dir /tmp/dist
      - uses: actions/upload-artifact@v2
        with:
          name: sovtokenfees-python
          path: /tmp/dist
          retention-days: 5